const state={income:400000,spending:220000,savings:80000,debt:1200000,score:72};
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-CR',{style:'currency',currency:'CRC',maximumFractionDigits:0}).format(n);
function renderFoundations(){const s=state.score;const status=s>=80?'EXCELLENT':s>=65?'GOOD':'NEEDS ATTENTION';$('dashboard').innerHTML=`
<section class="whoop-hero">
  <div class="hero-copy"><span class="eyebrow">FOUNDATIONS · FINANCIAL HEALTH</span><h2>You’re on track <b>♥</b></h2><p>Keep building healthy financial habits. Small steps compound.</p></div>
  <div class="score-orb"><div class="score-ring" style="--score:${s}%"><div><strong>${s}</strong><span>FINANCIAL HEALTH</span><em>${status}</em></div></div></div>
  <div class="delta-card"><strong>↗ +8</strong><span>vs. last week</span></div>
</section>
<section class="pace-card"><div class="section-head"><h3>FINANCIAL PACE</h3><span class="live-pill">● Improving vs. last month</span></div><div class="pace-track"><i></i><b style="left:${Math.min(94,Math.max(12,s))}%"></b></div><div class="pace-labels"><span>Needs Attention</span><span>On Track</span><span>Excellent</span></div></section>
<section><div class="section-head"><h3>KEY METRICS</h3><button class="ghost">Customize ⚙</button></div><div class="metric-grid">
${metric('▣','INCOME',state.income,'+6%','green')}${metric('◔','SPENDING',state.spending,'−12%','blue')}${metric('♧','SAVINGS',state.savings,'+15%','purple')}${metric('◎','DEBT',state.debt,'−5%','pink')}</div></section>
<section class="next-action"><div class="action-icon">ϟ</div><div><span class="eyebrow">NEXT BEST ACTION</span><h3>Move ₡25,000 to your emergency fund</h3><p>You’re 3 months away from your goal.</p></div><button class="action-btn" id="takeAction">Take Action</button></section>
<section><div class="section-head"><h3>INSIGHTS</h3><button class="ghost">See all →</button></div><article class="insight-card"><div class="insight-icon">▥</div><div><strong>Your spending on food has increased 18% this month.</strong><p>Consider setting a weekly limit to stay on track.</p></div><span>›</span></article></section>
<section class="foundation-panel"><div class="section-head"><div><span class="eyebrow">FOUNDATIONS</span><h3>Understand what shapes your score</h3></div><span>5 metrics</span></div><div class="foundation-list"><button data-detail="cashflow"><span>↔</span>Cash Flow <b>${Math.round(s*.96)}</b> ›</button><button data-detail="savings"><span>＋</span>Savings <b>${Math.round(s*.91)}</b> ›</button><button data-detail="spending"><span>◔</span>Spending <b>${Math.round(s*.88)}</b> ›</button><button data-detail="debt"><span>−</span>Debt <b>${Math.round(s*1.05)}</b> ›</button></div></section>`;
$('takeAction').onclick=()=>detail('savings');document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));}
function metric(icon,name,value,change,tone){return `<article class="whoop-metric ${tone}"><div class="metric-icon">${icon}</div><div><span>${name}</span><strong>${money(value)}</strong></div><b>${change}</b><div class="spark"><i></i><i></i><i></i><i></i><i></i></div></article>`}
function detail(type){const map={cashflow:['CASH FLOW','Your monthly margin is the foundation of your financial health.','Income minus spending and required debt payments determines how much room you have to build wealth.'],savings:['SAVINGS','Your savings create financial resilience.','Your emergency fund and monthly saving pace determine how prepared you are for unexpected expenses.'],spending:['SPENDING','Spending is measured relative to your income.','Keeping recurring and discretionary spending within a sustainable range protects your monthly margin.'],debt:['DEBT','Debt load affects the flexibility of your cash flow.','Tracking required payments against income helps Zenloth surface when debt deserves attention.']};const x=map[type]||map.savings;$('details').classList.remove('hidden');$('details').innerHTML=`<article class="detail-card"><button class="back-btn" id="back">← Foundations</button><span class="eyebrow">${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p><div class="detail-score"><strong>${state.score}</strong><span>Financial Health</span></div></article>`;$('back').onclick=()=>{$('details').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})};$('details').scrollIntoView({behavior:'smooth'});}
function boot(){renderFoundations();document.querySelectorAll('.bottom-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.section==='foundations'){ $('details').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'});}else if(b.dataset.section==='overview'){ $('details').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'});}else detail(b.dataset.section)});$('modeButton').onclick=()=>{document.body.classList.toggle('dark');$('modeButton').textContent=document.body.classList.contains('dark')?'☀':'◐'};}
boot();
